import AuthContextProvider from "@/contexts/AuthContext";
import { MainContextProvider } from "../contexts/MainContext";
import "./globals.css";

export const metadata = {
	title: "FigPic",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`w-full h-screen antialiased`}>
				<AuthContextProvider>
					<MainContextProvider>{children}</MainContextProvider>
				</AuthContextProvider>
			</body>
		</html>
	);
}
